package com.myspace.uhcsearchtest;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class client implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("ID")
	private java.lang.Integer id;
	@org.kie.api.definition.type.Label("Name")
	private java.lang.String name;
	@org.kie.api.definition.type.Label("Age")
	private java.lang.Integer age;
	@org.kie.api.definition.type.Label("Gender")
	private java.lang.Character gender;

	@org.kie.api.definition.type.Label("Validated?")
	private java.lang.Boolean validated;

	@org.kie.api.definition.type.Label(value = "Pronouns")
	private java.lang.String pronouns;

	public client() {
	}

	public java.lang.Integer getId() {
		return this.id;
	}

	public void setId(java.lang.Integer id) {
		this.id = id;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.Integer getAge() {
		return this.age;
	}

	public void setAge(java.lang.Integer age) {
		this.age = age;
	}

	public java.lang.Character getGender() {
		return this.gender;
	}

	public void setGender(java.lang.Character gender) {
		this.gender = gender;
	}

	@Override
	public String toString() {
		return super.toString() + "=[ID: " + id + "; Name: " + pronouns + " " + name + "; Age: " + age + "; Gender: " + gender + "; Validated? " + validated + "]";
	}

	public java.lang.Boolean getValidated() {
		return this.validated;
	}

	public void setValidated(java.lang.Boolean validated) {
		this.validated = validated;
	}

	public java.lang.String getPronouns() {
		return this.pronouns;
	}

	public void setPronouns(java.lang.String pronouns) {
		this.pronouns = pronouns;
	}

	public client(java.lang.Integer id, java.lang.String name,
			java.lang.Integer age, java.lang.Character gender,
			java.lang.Boolean validated, java.lang.String pronouns) {
		this.id = id;
		this.name = name;
		this.age = age;
		this.gender = gender;
		this.validated = validated;
		this.pronouns = pronouns;
	}
}