package com.myspace.uhcsearchtest;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class item implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("ID")
	private java.lang.Integer id;
	@org.kie.api.definition.type.Label("Name")
	private java.lang.String name;
	@org.kie.api.definition.type.Label("Value")
	private java.lang.Integer value;

	@org.kie.api.definition.type.Label("Quantity")
	private java.lang.Integer qtde;

	@org.kie.api.definition.type.Label(value = "Validated?")
	private java.lang.Boolean validated;

	public item() {
	}

	public java.lang.Integer getId() {
		return this.id;
	}

	public void setId(java.lang.Integer id) {
		this.id = id;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.Integer getValue() {
		return this.value;
	}

	public void setValue(java.lang.Integer value) {
		this.value = value;
	}

	public java.lang.Integer getQtde() {
		return this.qtde;
	}

	public void setQtde(java.lang.Integer qtde) {
		this.qtde = qtde;
	}

	@Override
	public String toString() {
		return super.toString() + "=[ID: " + id + "; Name: " + name
				+ "; Value: " + value + "; Quantity: " + qtde + "; Validated? " + validated + "]";
	}

	public java.lang.Boolean getValidated() {
		return this.validated;
	}

	public void setValidated(java.lang.Boolean validated) {
		this.validated = validated;
	}

	public item(java.lang.Integer id, java.lang.String name,
			java.lang.Integer value, java.lang.Integer qtde,
			java.lang.Boolean validated) {
		this.id = id;
		this.name = name;
		this.value = value;
		this.qtde = qtde;
		this.validated = validated;
	}

}