package com.myspace.uhcsearchtest;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class order implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "ID")
	private java.lang.Integer id;
	@org.kie.api.definition.type.Label(value = "Client")
	private com.myspace.uhcsearchtest.client client;
	@org.kie.api.definition.type.Label(value = "Itens")
	private java.util.List<com.myspace.uhcsearchtest.item> itens;
	@org.kie.api.definition.type.Label(value = "Total Amount")
	private java.lang.Integer totalAmount;

	public order() {
	}

	public java.lang.Integer getId() {
		return this.id;
	}

	public void setId(java.lang.Integer id) {
		this.id = id;
	}

	public com.myspace.uhcsearchtest.client getClient() {
		return this.client;
	}

	public void setClient(com.myspace.uhcsearchtest.client client) {
		this.client = client;
	}

	public java.util.List<com.myspace.uhcsearchtest.item> getItens() {
		return this.itens;
	}

	public void setItens(java.util.List<com.myspace.uhcsearchtest.item> itens) {
		this.itens = itens;
	}
	
	public void addItem(com.myspace.uhcsearchtest.item item){
	    this.itens.add(item);
	    increaseTotalAmount(item.getValue() * item.getQtde());
	}
	
	public java.lang.Integer getTotalAmount() {
		return this.totalAmount;
	}

	public void setTotalAmount(java.lang.Integer totalAmount) {
		this.totalAmount = totalAmount;
	}

    private void increaseTotalAmount(Integer amount) {
        this.setTotalAmount(this.getTotalAmount() + amount);
    }

	public order(java.lang.Integer id, com.myspace.uhcsearchtest.client client,
			java.util.List<com.myspace.uhcsearchtest.item> itens,
			java.lang.Integer totalAmount) {
		this.id = id;
		this.client = client;
		this.itens = itens;
		this.totalAmount = totalAmount;
	}
	
	@Override
	public String toString() {
	    return super.toString() + "={Client: " + client.toString() + "; Itens: " + itens.toString() + "; Total amount: " + totalAmount + "}";
	}

}